### PR TITLE
Update firebase tools

### PR DESCRIPTION
**Pull request by tdivoll**
This PR bumps up firebase-tools, which takes care of the majority of vulnerabilities. There seems to be one file related to `minimatch` that gets caught by the tscheck now: 
image

### CODE REVIEW

**Comment by tdivoll** [comment]
`minimatch` seems to be used by many of the `@types` packages and each uses a diff version. Adding an override on the `package.json` for one specific version seemed to work without issue.

**Comment by eldu** [comment]
> `minimatch` seems to be used by many of the `@types` packages and each uses a diff version. Adding an override on the `package.json` for one specific version seemed to work without issue.

@tdivoll Do you still experience the error?

**Comment by tdivoll** [comment]
> > `minimatch` seems to be used by many of the `@types` packages and each uses a diff version. Adding an override on the `package.json` for one specific version seemed to work without issue.
> 
> @tdivoll Do you still experience the error?

Adding the override block for the one particular version onf minimatch and glob seems to fix it. 
`},
    "overrides": {
    "minimatch": "5.1.2",
    "glob": "8.1.0"
  }`

**Comment by tdivoll** [comment]
@eldu, I do still get the same issue with minimatch if I remove the override. The CI doesn't pass unless I wipe `node_modules` and `package-lock.json` and reinstall. Then I get back to the same two errors about minimatch.

**Comment by eldu** [comment]
Closing in favor of #69

**Pull request closed without merging**
